# Generated by Django 4.2.5 on 2024-01-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_accountdetails_type_alter_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
