# Generated by Django 4.2.5 on 2024-01-01 06:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_is_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=accounts.models.default_image_path, upload_to='userprofile'),
        ),
    ]
