# Generated by Django 4.2.5 on 2024-01-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_applied',
            field=models.BooleanField(default=False),
        ),
    ]
